export const mockPages = [
  { title: 'The Secret Life of Urban Beekeepers' },
  { title: "5 Revolutionary Cooking Techniques You've Never Heard Of" },
  { title: 'Why Your Houseplants Are Secretly Stressed' },
  { title: 'The Forgotten History of Coffee Houses' },
  { title: 'Digital Minimalism: A 30-Day Challenge' },
  { title: 'The Science Behind Perfect Sourdough' },
  { title: 'Exploring Hidden Waterfalls in Southeast Asia' },
  { title: 'Modern Architecture Meets Sustainable Living' },
  { title: 'The Rise of Micro-Mobility in Cities' },
  { title: 'Understanding Quantum Computing for Beginners' },
  { title: 'The Art of Japanese Forest Bathing' },
  { title: 'How to Build a Smart Home on a Budget' },
  { title: 'The Psychology of Color in Web Design' },
  { title: 'Lost Languages of the Digital Age' },
  { title: 'Urban Farming: From Rooftop to Table' },
  { title: 'The Future of Remote Work Culture' },
  { title: 'Mindful Photography: Seeing the Unseen' },
  { title: 'The Hidden Mathematics of Snowflakes' },
  { title: 'Crafting the Perfect Morning Routine' },
  { title: 'Traditional Games in the Modern World' },
  { title: 'The Evolution of Street Art' },
  { title: 'Understanding Cloud Computing Basics' },
  { title: 'The Rise of Virtual Reality Tourism' },
  { title: 'Sustainable Fashion: Beyond the Buzzwords' },
  { title: 'The Art of Digital Decluttering' },
  { title: 'Ancient Remedies for Modern Stress' },
  { title: 'The Science of Perfect Pizza' },
  { title: 'Rediscovering Analog Hobbies' },
  { title: 'The Future of Electric Transportation' },
  { title: 'Mindfulness in the Digital Age' },
  { title: 'The Hidden World of Urban Wildlife' },
  { title: 'Mastering the Art of Time Blocking' },
  { title: 'The Psychology of Social Media' },
  { title: 'Adventures in Home Fermentation' },
  { title: 'Understanding Blockchain Technology' },
  { title: 'The Rise of Vertical Gardens' },
  { title: 'Digital Nomads: A Day in the Life' },
  { title: 'The Art of Minimalist Photography' },
  { title: 'Traditional Crafts in Modern Times' },
  { title: 'The Science of Better Sleep' },
  { title: 'Understanding Machine Learning' },
  { title: 'The Future of Remote Education' },
  { title: 'Exploring Underground Cities' },
  { title: 'The Psychology of Productivity' },
  { title: 'Sustainable Living in Small Spaces' },
  { title: 'The Art of Digital Storytelling' },
  { title: 'Ancient Philosophy for Modern Life' },
  { title: 'The Science of Perfect Coffee' },
  { title: 'Understanding Artificial Intelligence' },
  { title: 'The Rise of Smart Cities' },
  { title: 'Mindful Travel in the Modern World' },
  { title: 'The Hidden Life of House Dust' },
  { title: 'Mastering Remote Team Management' },
  { title: 'The Psychology of User Experience' },
  { title: 'Adventures in Urban Foraging' },
  { title: 'Understanding Edge Computing' },
  { title: 'The Rise of Digital Art' },
  { title: 'Traditional Medicine Meets Science' },
  { title: 'The Art of Virtual Collaboration' },
  { title: 'Modern Solutions for Ancient Problems' },
  { title: 'The Science of Human Connection' },
  { title: 'Understanding 5G Technology' },
  { title: 'The Future of Digital Privacy' },
  { title: 'Exploring Virtual Communities' },
  { title: 'The Psychology of Decision Making' },
  { title: 'Sustainable Technology Trends' },
  { title: 'The Art of Data Visualization' },
  { title: 'Ancient Wisdom in Modern Business' },
  { title: 'The Science of Habit Formation' },
  { title: 'Understanding Quantum Physics' },
  { title: 'The Rise of Digital Currencies' },
  { title: 'Mindful Gaming: Finding Balance' },
  { title: 'The Hidden World of Microbes' },
  { title: 'Mastering Digital Communication' },
  { title: 'The Psychology of Creative Thinking' },
  { title: 'Adventures in Home Automation' },
  { title: 'Understanding Neural Networks' },
  { title: 'The Rise of Sustainable Energy' },
  { title: 'Traditional Dance in Modern Fitness' },
  { title: 'The Art of Personal Branding' },
  { title: 'Modern Myths and Urban Legends' },
  { title: 'The Science of Memory' },
  { title: 'Understanding Cloud Security' },
  { title: 'The Future of Public Transport' },
  { title: 'Exploring Digital Gardens' },
  { title: 'The Psychology of Color Theory' },
  { title: 'Sustainable Home Design' },
  { title: 'The Art of Remote Leadership' },
  { title: 'Ancient Games in Digital Form' },
  { title: 'The Science of Happiness' },
  { title: 'Understanding IoT Devices' },
  { title: 'The Rise of Digital Health' },
  { title: 'Mindful Social Media Usage' },
  { title: 'The Hidden Life of City Trees' },
  { title: 'Mastering Virtual Presentations' },
  { title: 'The Psychology of Learning' },
  { title: 'Adventures in Digital Art' },
  { title: 'Understanding Big Data' },
  { title: 'The Rise of Smart Homes' },
  { title: 'Traditional Music in the Digital Age' },
] as const
